wandb_version: 1

vocab_size:
  desc: null
  value: 10
seq_length:
  desc: null
  value: 20
n_layers:
  desc: null
  value: 2
lr:
  desc: null
  value: 1.0
n_heads:
  desc: null
  value:
  - 1
  - 1
d_out:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 1024
alpha:
  desc: null
  value: 0.1
seed:
  desc: null
  value: 2024
ignore_idx:
  desc: null
  value: -100
n_sample:
  desc: null
  value: 16777216
device:
  desc: null
  value: cuda:0
enable_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711038307.177924
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
